### PR TITLE
Fix net.i2p.crypto-4.0.0 jar conflicts

### PR DESCRIPTION
**Pull request by drEfrati**
- Remove the crypto jar from the stellar sdk and just add a new dependency in gradle instead of that jar.
- Also rename the ed25519-sha-512 string in KeyPair class because of the crypto jar dependency change.

* invoked all the tests and they passed

### CODE REVIEW

**Comment by yosriz** [comment]
@drEfrati please open PR as well at android-stellar-sdk level, also merge this change to master (I'll merge export import branch to master)

**Review by yosriz — CHANGES_REQUESTED** [review]
@drEfrati please open PR as well at android-stellar-sdk level, also merge this change to master (I'll merge export import branch to master)

**Comment by drEfrati** [comment]
@yosriz tried to open a PR for the stellar sdk part but couldn't add reviewers so I probably didn't do it correctly.
Also add the new crypto library const also like we did for the "kin-sdk"

**Comment by drEfrati** [comment]
@yosriz also changed the name of the pull request

**Review by yosriz — APPROVED** [review]

**Pull request merged**
