### PR TITLE
change stellar sdk dependency, remove default proguard config

### PR DESCRIPTION
**Pull request by yosriz**
* change stellar sdk to kinfoundation android-stellar-sdk (latest master)
* remove default proguard config from lib (let hosting app decide)

### CODE REVIEW

**Comment by OrenZak** [comment]
@yosriz  you can remove espresso dependency and also the gradle tasks (prepareRPC, cleanRPC) we created to run testrpc.

**Comment by yosriz** [comment]
@OrenZak, didn't handle tests yet, currently the tests are even not passed, will handle all tests + configurations in a different task/PR

**Comment by OrenZak** [comment]
Sure as you wish, but it's related to gradle  :)

**Review by OrenZak — APPROVED** [review]
👍

**Pull request merged**
